### PR TITLE
Changes made to my repo by sdpenguin

### PR DESCRIPTION
**Pull request by bamford**
Existence of this fork brought to my attention by Jakub Mikulski.

Creating a pull request to examine changes. Could consider merging them in, if and when I return to this project.

### CODE REVIEW

**Comment by bamford** [comment]
From a skim through these generally look pretty sensible. Obviously need to have a go at testing first, and check how it integrates with my extensions to the original DC15 work.

**Comment by bamford** [comment]
Hi @sdpenguin! I've recently discovered that you spent some time refactoring this code a few years ago. I was just wondering if you used it for anything interesting?

**Comment by bamford** [comment]
Merging on to `sdpenguin` branch in my repo so I can make changes before merging into my master.

**Comment by sdpenguin** [comment]
I’m glad this was useful and thanks for merging. I did actually use this to experiment with SNNs a while back, to investigate how things worked! I might reuse it again in future.

**Pull request merged**
